sg_prior:
  SG_1: 4
  SG_102: 1
  SG_107: 1
  SG_109: 1
  SG_11: 3
  SG_113: 1
  SG_118: 1
  SG_12: 11
  SG_121: 2
  SG_123: 7
  SG_124: 1
  SG_127: 1
  SG_129: 5
  SG_13: 2
  SG_136: 1
  SG_139: 6
  SG_14: 3
  SG_141: 1
  SG_147: 1
  SG_148: 2
  SG_15: 2
  SG_155: 1
  SG_156: 3
  SG_160: 2
  SG_164: 10
  SG_166: 3
  SG_176: 1
  SG_18: 1
  SG_186: 1
  SG_187: 4
  SG_189: 3
  SG_191: 4
  SG_194: 13
  SG_198: 1
  SG_2: 5
  SG_216: 2
  SG_221: 3
  SG_223: 1
  SG_224: 1
  SG_225: 27
  SG_26: 2
  SG_31: 1
  SG_38: 3
  SG_4: 1
  SG_43: 2
  SG_44: 1
  SG_5: 1
  SG_55: 1
  SG_6: 4
  SG_62: 9
  SG_63: 6
  SG_65: 2
  SG_71: 4
  SG_72: 1
  SG_74: 2
  SG_79: 1
  SG_8: 6
  SG_82: 4
  SG_83: 1
  SG_84: 1
  SG_86: 1
  SG_9: 1
  SG_90: 1
  SG_99: 1
